export interface ITool {
    _id : string,
    name : string, 
    code : string, 
    angle : number,
    diameter : number,
    size : number,
    material : string,
    height : number,
    machine : string,
    dateIn : Date,
    dateOut : Date,
    status : string,
    description : string,
}